  // ======================================================================
  // 5. 样式
  // ======================================================================

  var CSS_TEXT = [
    '.dsh-ad-popup{position:fixed;width:268px;box-sizing:border-box;border:2px solid #1b1b1b;',
    'border-radius:10px;overflow:hidden;background:#fff;color:var(--ad-ink);',
    'font:400 13px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;',
    'box-shadow:0 14px 34px rgba(0,0,0,.34);pointer-events:auto;will-change:transform,opacity}',
    '.dsh-ad-popup.dsh-ad-in{animation:dshAdIn .28s cubic-bezier(.2,1.4,.4,1) both}',
    '.dsh-ad-popup.dsh-ad-out{animation:dshAdOut .17s ease-in both}',
    '@keyframes dshAdIn{from{opacity:0;transform:scale(.86) translateY(14px)}to{opacity:1;transform:none}}',
    '@keyframes dshAdOut{to{opacity:0;transform:scale(.94) translateY(8px)}}',
    '.dsh-ad-bar{display:flex;align-items:center;gap:6px;padding:4px 8px;background:linear-gradient(90deg,var(--ad-from),var(--ad-to));',
    'border-bottom:2px solid #1b1b1b;font-size:11px;font-weight:700;color:var(--ad-ink)}',
    '.dsh-ad-dot{width:8px;height:8px;border-radius:50%;background:#ff3b30;box-shadow:0 0 0 2px rgba(0,0,0,.15);flex:none}',
    '.dsh-ad-bartext{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
    '.dsh-ad-body{padding:10px 12px 12px;background:linear-gradient(160deg,var(--ad-from),var(--ad-to))}',
    '.dsh-ad-kicker{display:inline-block;padding:1px 7px;border:1.5px solid var(--ad-ink);border-radius:999px;',
    'font-size:10px;font-weight:800;letter-spacing:.06em;background:var(--ad-accent);color:var(--ad-ink)}',
    '.dsh-ad-title{margin:7px 0 5px;font-size:17px;font-weight:800;line-height:1.25;text-shadow:0 1px 0 rgba(255,255,255,.35)}',
    '.dsh-ad-text{font-size:12px;opacity:.92}',
    '.dsh-ad-marquee{margin:8px 0;padding:3px 0;background:#1b1b1b;color:#ffe066;font-size:11px;',
    'white-space:nowrap;overflow:hidden;border-radius:3px}',
    '.dsh-ad-marquee-inner{display:inline-block;padding-left:100%;animation:dshAdMarquee 9s linear infinite}',
    '@keyframes dshAdMarquee{to{transform:translateX(-100%)}}',
    '.dsh-ad-actions{display:flex;gap:8px;margin-top:2px}',
    '.dsh-ad-cta{flex:1;padding:7px 10px;border:2px solid #1b1b1b;border-radius:7px;cursor:pointer;',
    'background:var(--ad-accent);color:var(--ad-ink);font-size:13px;font-weight:800;',
    'box-shadow:0 3px 0 #1b1b1b;animation:dshAdPulse 1.6s ease-in-out infinite}',
    '.dsh-ad-cta:active{transform:translateY(2px);box-shadow:0 1px 0 #1b1b1b}',
    '@keyframes dshAdPulse{0%,100%{filter:brightness(1)}50%{filter:brightness(1.18)}}',
    '.dsh-ad-foot{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:9px}',
    '.dsh-ad-disclaimer{font-size:9.5px;opacity:.72;line-height:1.2}',
    '.dsh-ad-close{flex:none;padding:4px 10px;border:2px solid #1b1b1b;border-radius:6px;cursor:pointer;',
    'background:#fff;color:#1b1b1b;font-size:11px;font-weight:700;transition:transform .18s ease,background .15s ease;white-space:nowrap}',
    '.dsh-ad-close:hover{background:#ffe066}',
    '.dsh-ad-shake{animation:dshAdShake .4s ease-in-out}',
    '@keyframes dshAdShake{0%,100%{transform:none}25%{transform:translateX(-4px) rotate(-1deg)}75%{transform:translateX(4px) rotate(1deg)}}',
    '.dsh-ad-nudge{animation:dshAdNudge .42s ease-in-out}',
    '@keyframes dshAdNudge{0%,100%{transform:none}30%{transform:translateY(-3px) scale(1.012)}70%{transform:translateY(2px)}}',
    '.dsh-ad-badge{position:fixed;right:12px;bottom:8px;z-index:9999;display:flex;align-items:center;gap:6px;',
    'padding:3px 6px 3px 9px;border-radius:999px;background:rgba(20,20,20,.72);color:#fff;cursor:pointer;',
    'font:500 11px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;',
    'backdrop-filter:blur(6px);box-shadow:0 4px 14px rgba(0,0,0,.25);opacity:.55;transition:opacity .18s ease}',
    '.dsh-ad-badge:hover{opacity:1}',
    '.dsh-ad-badge-muted{opacity:.35}',
    '.dsh-ad-badge-text{white-space:nowrap}',
    '.dsh-ad-badge-btn{border:none;border-radius:999px;padding:2px 8px;cursor:pointer;background:rgba(255,255,255,.18);',
    'color:#fff;font-size:11px}',
    '.dsh-ad-badge-btn:hover{background:rgba(255,255,255,.32)}',
    // ---- 设置面板(页面内打开,不依赖新窗口) ----
    '.dsh-ad-mask{position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.5);display:flex;',
    'align-items:center;justify-content:center;padding:20px;backdrop-filter:blur(2px)}',
    '.dsh-ad-panel{width:min(680px,100%);max-height:88vh;display:flex;flex-direction:column;',
    'background:#fff;color:#1b1b1b;border:1px solid #e4e4e7;border-radius:14px;overflow:hidden;',
    'box-shadow:0 24px 60px rgba(0,0,0,.4);',
    'font:400 13px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif}',
    '@media (prefers-color-scheme:dark){.dsh-ad-panel{background:#1f1f23;color:#ececf1;border-color:#2e2e33}}',
    '.dsh-ad-panel-head{display:flex;align-items:center;justify-content:space-between;gap:10px;',
    'padding:12px 16px;border-bottom:1px solid rgba(128,128,128,.25)}',
    '.dsh-ad-panel-title{font-size:15px;font-weight:600}',
    '.dsh-ad-panel-x{border:none;background:transparent;color:inherit;font-size:15px;cursor:pointer;',
    'border-radius:6px;padding:2px 8px;opacity:.7}',
    '.dsh-ad-panel-x:hover{opacity:1;background:rgba(128,128,128,.18)}',
    '.dsh-ad-panel-body{padding:14px 16px 16px;overflow:auto;display:flex;flex-direction:column;gap:10px}',
    '.dsh-ad-note{font-size:12px;opacity:.72;line-height:1.55}',
    '.dsh-ad-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}',
    '.dsh-ad-row-toggle{cursor:pointer;user-select:none;font-weight:600}',
    '.dsh-ad-panel-status{font-size:12px;opacity:.8;min-height:18px}',
    '@media (max-width:720px){.dsh-ad-popup{width:236px}.dsh-ad-title{font-size:15px}}',
  ].join('')
